sonar.projectKey=handsome-Druid_AICheck
sonar.projectName=AICheck
sonar.projectVersion=0.1.0
sonar.organization=handsome-druid

# Path to sources
sonar.sources=src
sonar.exclusions=**/__pycache__/**, .venv/**, output/**, src/views/ui/**, **/.git/**, **/.github/**, **/.vscode/**, **/.devcontainer/**

# Path to tests
sonar.tests=tests
sonar.test.inclusions=tests/**
# sonar.test.exclusions=

sonar.python.version=3.14

# Source encoding
sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=