sonar.projectKey=handsome-Druid_AICheck
sonar.projectName=AICheck
sonar.projectVersion=0.1.0
sonar.organization=handsome-druid

sonar.sources=src
sonar.python.version=3.14

sonar.exclusions=**/__pycache__/**, .venv/**, output/**, src/views/ui/**, **/.git/**, **/.vscode/**, **/.devcontainer/**

sonar.sourceEncoding=UTF-8

