sonar.projectKey=handsome-Druid_AICheck
sonar.projectName=AICheck
sonar.projectVersion=0.1.0
sonar.organization=handsome-druid

sonar.sources=src

sonar.exclusions=**/__pycache__/**, .venv/**, output/**

sonar.sourceEncoding=UTF-8

